// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllConfig.proto

#ifndef PROTOBUF_AllConfig_2eproto__INCLUDED
#define PROTOBUF_AllConfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ActivityConfig.pb.h"
#include "MineCardCountConfig.pb.h"
#include "MineCoinConfig.pb.h"
#include "DailyEventConfig.pb.h"
#include "MineInitDataConfig.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_AllConfig_2eproto();
void protobuf_AssignDesc_AllConfig_2eproto();
void protobuf_ShutdownFile_AllConfig_2eproto();

class AllConfig;

// ===================================================================

class AllConfig : public ::google::protobuf::Message {
 public:
  AllConfig();
  virtual ~AllConfig();

  AllConfig(const AllConfig& from);

  inline AllConfig& operator=(const AllConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllConfig& default_instance();

  void Swap(AllConfig* other);

  // implements Message ----------------------------------------------

  AllConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AllConfig& from);
  void MergeFrom(const AllConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ActivityConfig activity = 1;
  inline int activity_size() const;
  inline void clear_activity();
  static const int kActivityFieldNumber = 1;
  inline const ::ActivityConfig& activity(int index) const;
  inline ::ActivityConfig* mutable_activity(int index);
  inline ::ActivityConfig* add_activity();
  inline const ::google::protobuf::RepeatedPtrField< ::ActivityConfig >&
      activity() const;
  inline ::google::protobuf::RepeatedPtrField< ::ActivityConfig >*
      mutable_activity();

  // repeated .MineCardCountConfig minecardcount = 2;
  inline int minecardcount_size() const;
  inline void clear_minecardcount();
  static const int kMinecardcountFieldNumber = 2;
  inline const ::MineCardCountConfig& minecardcount(int index) const;
  inline ::MineCardCountConfig* mutable_minecardcount(int index);
  inline ::MineCardCountConfig* add_minecardcount();
  inline const ::google::protobuf::RepeatedPtrField< ::MineCardCountConfig >&
      minecardcount() const;
  inline ::google::protobuf::RepeatedPtrField< ::MineCardCountConfig >*
      mutable_minecardcount();

  // repeated .MineCoinConfig minecoin = 3;
  inline int minecoin_size() const;
  inline void clear_minecoin();
  static const int kMinecoinFieldNumber = 3;
  inline const ::MineCoinConfig& minecoin(int index) const;
  inline ::MineCoinConfig* mutable_minecoin(int index);
  inline ::MineCoinConfig* add_minecoin();
  inline const ::google::protobuf::RepeatedPtrField< ::MineCoinConfig >&
      minecoin() const;
  inline ::google::protobuf::RepeatedPtrField< ::MineCoinConfig >*
      mutable_minecoin();

  // repeated .DailyEventConfig dailyevent = 4;
  inline int dailyevent_size() const;
  inline void clear_dailyevent();
  static const int kDailyeventFieldNumber = 4;
  inline const ::DailyEventConfig& dailyevent(int index) const;
  inline ::DailyEventConfig* mutable_dailyevent(int index);
  inline ::DailyEventConfig* add_dailyevent();
  inline const ::google::protobuf::RepeatedPtrField< ::DailyEventConfig >&
      dailyevent() const;
  inline ::google::protobuf::RepeatedPtrField< ::DailyEventConfig >*
      mutable_dailyevent();

  // repeated .MineInitDataConfig mineinitdata = 5;
  inline int mineinitdata_size() const;
  inline void clear_mineinitdata();
  static const int kMineinitdataFieldNumber = 5;
  inline const ::MineInitDataConfig& mineinitdata(int index) const;
  inline ::MineInitDataConfig* mutable_mineinitdata(int index);
  inline ::MineInitDataConfig* add_mineinitdata();
  inline const ::google::protobuf::RepeatedPtrField< ::MineInitDataConfig >&
      mineinitdata() const;
  inline ::google::protobuf::RepeatedPtrField< ::MineInitDataConfig >*
      mutable_mineinitdata();

  // @@protoc_insertion_point(class_scope:AllConfig)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ActivityConfig > activity_;
  ::google::protobuf::RepeatedPtrField< ::MineCardCountConfig > minecardcount_;
  ::google::protobuf::RepeatedPtrField< ::MineCoinConfig > minecoin_;
  ::google::protobuf::RepeatedPtrField< ::DailyEventConfig > dailyevent_;
  ::google::protobuf::RepeatedPtrField< ::MineInitDataConfig > mineinitdata_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_AllConfig_2eproto();
  friend void protobuf_AssignDesc_AllConfig_2eproto();
  friend void protobuf_ShutdownFile_AllConfig_2eproto();

  void InitAsDefaultInstance();
  static AllConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// AllConfig

// repeated .ActivityConfig activity = 1;
inline int AllConfig::activity_size() const {
  return activity_.size();
}
inline void AllConfig::clear_activity() {
  activity_.Clear();
}
inline const ::ActivityConfig& AllConfig::activity(int index) const {
  return activity_.Get(index);
}
inline ::ActivityConfig* AllConfig::mutable_activity(int index) {
  return activity_.Mutable(index);
}
inline ::ActivityConfig* AllConfig::add_activity() {
  return activity_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ActivityConfig >&
AllConfig::activity() const {
  return activity_;
}
inline ::google::protobuf::RepeatedPtrField< ::ActivityConfig >*
AllConfig::mutable_activity() {
  return &activity_;
}

// repeated .MineCardCountConfig minecardcount = 2;
inline int AllConfig::minecardcount_size() const {
  return minecardcount_.size();
}
inline void AllConfig::clear_minecardcount() {
  minecardcount_.Clear();
}
inline const ::MineCardCountConfig& AllConfig::minecardcount(int index) const {
  return minecardcount_.Get(index);
}
inline ::MineCardCountConfig* AllConfig::mutable_minecardcount(int index) {
  return minecardcount_.Mutable(index);
}
inline ::MineCardCountConfig* AllConfig::add_minecardcount() {
  return minecardcount_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MineCardCountConfig >&
AllConfig::minecardcount() const {
  return minecardcount_;
}
inline ::google::protobuf::RepeatedPtrField< ::MineCardCountConfig >*
AllConfig::mutable_minecardcount() {
  return &minecardcount_;
}

// repeated .MineCoinConfig minecoin = 3;
inline int AllConfig::minecoin_size() const {
  return minecoin_.size();
}
inline void AllConfig::clear_minecoin() {
  minecoin_.Clear();
}
inline const ::MineCoinConfig& AllConfig::minecoin(int index) const {
  return minecoin_.Get(index);
}
inline ::MineCoinConfig* AllConfig::mutable_minecoin(int index) {
  return minecoin_.Mutable(index);
}
inline ::MineCoinConfig* AllConfig::add_minecoin() {
  return minecoin_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MineCoinConfig >&
AllConfig::minecoin() const {
  return minecoin_;
}
inline ::google::protobuf::RepeatedPtrField< ::MineCoinConfig >*
AllConfig::mutable_minecoin() {
  return &minecoin_;
}

// repeated .DailyEventConfig dailyevent = 4;
inline int AllConfig::dailyevent_size() const {
  return dailyevent_.size();
}
inline void AllConfig::clear_dailyevent() {
  dailyevent_.Clear();
}
inline const ::DailyEventConfig& AllConfig::dailyevent(int index) const {
  return dailyevent_.Get(index);
}
inline ::DailyEventConfig* AllConfig::mutable_dailyevent(int index) {
  return dailyevent_.Mutable(index);
}
inline ::DailyEventConfig* AllConfig::add_dailyevent() {
  return dailyevent_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DailyEventConfig >&
AllConfig::dailyevent() const {
  return dailyevent_;
}
inline ::google::protobuf::RepeatedPtrField< ::DailyEventConfig >*
AllConfig::mutable_dailyevent() {
  return &dailyevent_;
}

// repeated .MineInitDataConfig mineinitdata = 5;
inline int AllConfig::mineinitdata_size() const {
  return mineinitdata_.size();
}
inline void AllConfig::clear_mineinitdata() {
  mineinitdata_.Clear();
}
inline const ::MineInitDataConfig& AllConfig::mineinitdata(int index) const {
  return mineinitdata_.Get(index);
}
inline ::MineInitDataConfig* AllConfig::mutable_mineinitdata(int index) {
  return mineinitdata_.Mutable(index);
}
inline ::MineInitDataConfig* AllConfig::add_mineinitdata() {
  return mineinitdata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MineInitDataConfig >&
AllConfig::mineinitdata() const {
  return mineinitdata_;
}
inline ::google::protobuf::RepeatedPtrField< ::MineInitDataConfig >*
AllConfig::mutable_mineinitdata() {
  return &mineinitdata_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AllConfig_2eproto__INCLUDED
