// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllPbsName.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AllPbsName.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* AllPbsName_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AllPbsName_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AllPbsName_2eproto() {
  protobuf_AddDesc_AllPbsName_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AllPbsName.proto");
  GOOGLE_CHECK(file != NULL);
  AllPbsName_descriptor_ = file->message_type(0);
  static const int AllPbsName_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AllPbsName, all_sheets_),
  };
  AllPbsName_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AllPbsName_descriptor_,
      AllPbsName::default_instance_,
      AllPbsName_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AllPbsName, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AllPbsName, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AllPbsName));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AllPbsName_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AllPbsName_descriptor_, &AllPbsName::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AllPbsName_2eproto() {
  delete AllPbsName::default_instance_;
  delete AllPbsName_reflection_;
}

void protobuf_AddDesc_AllPbsName_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020AllPbsName.proto\" \n\nAllPbsName\022\022\n\nall_"
    "sheets\030\001 \003(\t", 52);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AllPbsName.proto", &protobuf_RegisterTypes);
  AllPbsName::default_instance_ = new AllPbsName();
  AllPbsName::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AllPbsName_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AllPbsName_2eproto {
  StaticDescriptorInitializer_AllPbsName_2eproto() {
    protobuf_AddDesc_AllPbsName_2eproto();
  }
} static_descriptor_initializer_AllPbsName_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AllPbsName::kAllSheetsFieldNumber;
#endif  // !_MSC_VER

AllPbsName::AllPbsName()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AllPbsName::InitAsDefaultInstance() {
}

AllPbsName::AllPbsName(const AllPbsName& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AllPbsName::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AllPbsName::~AllPbsName() {
  SharedDtor();
}

void AllPbsName::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AllPbsName::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AllPbsName::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AllPbsName_descriptor_;
}

const AllPbsName& AllPbsName::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AllPbsName_2eproto();
  return *default_instance_;
}

AllPbsName* AllPbsName::default_instance_ = NULL;

AllPbsName* AllPbsName::New() const {
  return new AllPbsName;
}

void AllPbsName::Clear() {
  all_sheets_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AllPbsName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string all_sheets = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_all_sheets:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_all_sheets()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->all_sheets(this->all_sheets_size() - 1).data(),
            this->all_sheets(this->all_sheets_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_all_sheets;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AllPbsName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string all_sheets = 1;
  for (int i = 0; i < this->all_sheets_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->all_sheets(i).data(), this->all_sheets(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->all_sheets(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AllPbsName::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string all_sheets = 1;
  for (int i = 0; i < this->all_sheets_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->all_sheets(i).data(), this->all_sheets(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->all_sheets(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AllPbsName::ByteSize() const {
  int total_size = 0;

  // repeated string all_sheets = 1;
  total_size += 1 * this->all_sheets_size();
  for (int i = 0; i < this->all_sheets_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->all_sheets(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AllPbsName::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AllPbsName* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AllPbsName*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AllPbsName::MergeFrom(const AllPbsName& from) {
  GOOGLE_CHECK_NE(&from, this);
  all_sheets_.MergeFrom(from.all_sheets_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AllPbsName::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AllPbsName::CopyFrom(const AllPbsName& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AllPbsName::IsInitialized() const {

  return true;
}

void AllPbsName::Swap(AllPbsName* other) {
  if (other != this) {
    all_sheets_.Swap(&other->all_sheets_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AllPbsName::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AllPbsName_descriptor_;
  metadata.reflection = AllPbsName_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
