// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AllPbsName.proto

#ifndef PROTOBUF_AllPbsName_2eproto__INCLUDED
#define PROTOBUF_AllPbsName_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_AllPbsName_2eproto();
void protobuf_AssignDesc_AllPbsName_2eproto();
void protobuf_ShutdownFile_AllPbsName_2eproto();

class AllPbsName;

// ===================================================================

class AllPbsName : public ::google::protobuf::Message {
 public:
  AllPbsName();
  virtual ~AllPbsName();

  AllPbsName(const AllPbsName& from);

  inline AllPbsName& operator=(const AllPbsName& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllPbsName& default_instance();

  void Swap(AllPbsName* other);

  // implements Message ----------------------------------------------

  AllPbsName* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AllPbsName& from);
  void MergeFrom(const AllPbsName& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string all_sheets = 1;
  inline int all_sheets_size() const;
  inline void clear_all_sheets();
  static const int kAllSheetsFieldNumber = 1;
  inline const ::std::string& all_sheets(int index) const;
  inline ::std::string* mutable_all_sheets(int index);
  inline void set_all_sheets(int index, const ::std::string& value);
  inline void set_all_sheets(int index, const char* value);
  inline void set_all_sheets(int index, const char* value, size_t size);
  inline ::std::string* add_all_sheets();
  inline void add_all_sheets(const ::std::string& value);
  inline void add_all_sheets(const char* value);
  inline void add_all_sheets(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& all_sheets() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_all_sheets();

  // @@protoc_insertion_point(class_scope:AllPbsName)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> all_sheets_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_AllPbsName_2eproto();
  friend void protobuf_AssignDesc_AllPbsName_2eproto();
  friend void protobuf_ShutdownFile_AllPbsName_2eproto();

  void InitAsDefaultInstance();
  static AllPbsName* default_instance_;
};
// ===================================================================


// ===================================================================

// AllPbsName

// repeated string all_sheets = 1;
inline int AllPbsName::all_sheets_size() const {
  return all_sheets_.size();
}
inline void AllPbsName::clear_all_sheets() {
  all_sheets_.Clear();
}
inline const ::std::string& AllPbsName::all_sheets(int index) const {
  return all_sheets_.Get(index);
}
inline ::std::string* AllPbsName::mutable_all_sheets(int index) {
  return all_sheets_.Mutable(index);
}
inline void AllPbsName::set_all_sheets(int index, const ::std::string& value) {
  all_sheets_.Mutable(index)->assign(value);
}
inline void AllPbsName::set_all_sheets(int index, const char* value) {
  all_sheets_.Mutable(index)->assign(value);
}
inline void AllPbsName::set_all_sheets(int index, const char* value, size_t size) {
  all_sheets_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AllPbsName::add_all_sheets() {
  return all_sheets_.Add();
}
inline void AllPbsName::add_all_sheets(const ::std::string& value) {
  all_sheets_.Add()->assign(value);
}
inline void AllPbsName::add_all_sheets(const char* value) {
  all_sheets_.Add()->assign(value);
}
inline void AllPbsName::add_all_sheets(const char* value, size_t size) {
  all_sheets_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AllPbsName::all_sheets() const {
  return all_sheets_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AllPbsName::mutable_all_sheets() {
  return &all_sheets_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AllPbsName_2eproto__INCLUDED
